### ISSUE TITLE
Cannot read property 'destroy' of undefined after latest update

### ISSUE THREAD

**Issue by ankitgupta2k** [DockStation/dockstation#173] opened 2019-04-02 09:44 UTC
My container is running but I am unable to see the same in the dock station and instead seeing this error : Cannot read property 'destroy' of undefined. This is happening post update to new version.

**Comment by igor-lemon** [comment] 2019-04-02 10:17
Please, make an screenshot

**Comment by igor-lemon** [comment] 2019-04-02 11:31
If you want fast fix we need more information about how to reproduce it.

**Comment by ankitgupta2k** [comment] 2019-04-02 11:35
Thanks for quick reply. I am able to workaround this currently by uninstalling  and doing a fresh installation. 
But this issue has happened more than once and will take screenshot next time it occurs. I didn't take the screenshot for the last occurrence.
But the error was displayed in containers tab.

**Comment by igor-lemon** [comment] 2019-04-02 11:43
Do you remember steps to reproduce this?
Maybe some like click on Containers tabs, click on a second container, view stats, back to logs view, click on a first container...

**Comment by ankitgupta2k** [comment] 2019-04-02 12:38
I stopped the existing running container. The container was started with docker --rm command so on stop it was removed. After that I did docker run and the container is running successfully, But in dock station when I click on projects and then back to containers tab for refresh. I get the mentioned error. 
Seems if container is started with auto remove command on stop, the dockstation somehow is trying to destroy which is already destroyed by docker.

**Comment by ankitgupta2k** [comment] 2019-04-02 13:46
So its happening when I restart the container through docker, which was removed when I stopped.
![image](https://user-images.githubusercontent.com/30268160/55407577-79303500-555e-11e9-9b0a-d1b95898fac4.png)

**Comment by igor-lemon** [comment] 2019-04-02 13:47
Ok. Thanks for the info. We'll try to reproduce this and fix ASAP

**Comment by ankitgupta2k** [comment] 2019-04-04 08:12
One more issue also I noticed is when I am running two containers with master-slave config. I see the performance of dock station to have degraded poorly. It becomes unresponsive for long lengths of time. Mostly the container tab keep flickering and doesn't load most times.

**Comment by igor-lemon** [comment] 2019-04-04 12:59
Do you have many logs?
Because we found a bottleneck. It relates with big logs rendering.

**Comment by ankitgupta2k** [comment] 2019-04-04 16:08
How do I persist the log ? In order to send here.

**Comment by igor-lemon** [comment] 2019-04-04 18:57
I don't need logs. You can say me size of logs in MB.

**Comment by ankitgupta2k** [comment] 2019-04-05 11:29
Pardon my ignorance, how do I see how much log is generated in dock station and where ? I can just see the logs in containers.

**Comment by igor-lemon** [comment] 2019-04-09 01:08
So. It doesn't matter. We found a reason. Will publish fixes and logs views improvements soon.

**Comment by igor-lemon** [comment] 2019-04-15 20:52
Fixed in 1.5.1

**Closed by igor-lemon** 2019-04-15 20:52 UTC
