### ISSUE TITLE
Dockstation looses projects list

### ISSUE THREAD

**Issue by aldoanizio** [DockStation/dockstation#127] opened 2018-08-03 13:23 UTC
Sometimes Dockstation looses all projects list.

Even when closing the app correctly (stop all containers, close the app), on the next start the project list is empty.

Checking the 'Settins' json file I noticed that the array is empty.

I have this problem in this two tested scenarios:

Ubuntu 16.04 LTS
Elementary OS Loki

**Comment by igor-lemon** [comment] 2018-08-03 14:27
Hi @aldoanizio Thanks for the issue. Yes, we know about this bug but we couldn't reproduce it on the production app. Only only Linux and only dev version. But we didn't find any stable ways how to reproduce it. Maybe do you know some ways how to reproduce this bug with high probability?

**Comment by aldoanizio** [comment] 2018-08-03 19:02
Hi @igor-lemon. Thanks for the quick reply.

I'll make some tests today and tomorrow and I'll report to you.

**Comment by igor-lemon** [comment] 2018-08-03 19:49
Thank you so much!

**Comment by aldoanizio** [comment] 2018-08-04 21:32
Hi @igor-lemon 

After made some tests I noticed that the 'Settings' json file looses his content at the app shutdown. Another interesting case is that the problem is intermittent.

It happens randomly without any kind of standard.

What I did was monitoring the file content all the times at app startup and app shutdown.

I've monitored the file content in this scenarios.

-> Startup the app at the first time of day and shutdown the app at the end of day without shutdown the SO
-> Startup the app at the first time of day, shutdown the app in the middle of day, with the SO already booted startup the app again, shutdown the app after some hours of work (theese steps was repeated at least 4 times because I thought the cause of problem could be related to access some mounted partitions where the projects are stored)

The curious case is when the file looses the content, everything is erased, not even an empty json is stored, the file remains blank with 0 bytes of filesize.

If I could help doing some other kind of tests please let me know.

Thanks in advance and regards from Brazil.

**Comment by igor-lemon** [comment] 2018-08-06 21:40
Ok, thank you so much...
So, I think it doesn't matter, I think will be better if we use some different library for working with app settings. 
Thanks for the issue. I'll inform you when we fix this trouble. Will keep in touch!

**Comment by aldoanizio** [comment] 2018-09-04 20:57
One thing that I did to 'solve' temporarily the problem is create a backup settings file in the same folder.

Everytime the project list is changed I manually create the backup file with current settings and instead initialize the app using default gnome menu icon I've created a bash that replaces the original settings file and so starts the app.

This has been working without any problem. So if was too hard to replace the settings lib maybe you can implement such a thing in code level.

Hope it helps.

**Comment by igor-lemon** [comment] 2018-11-28 00:13
Hi @aldoanizio 
I have good news. We dropped a total library for working with app settings and started using another lib. 
So, in developer mode, we don't lose any projects it means this issue will be fixed in v1.5.

**Closed** 2019-04-01 16:48 UTC
